logging:
  logs:
    default:
      level: INFO

# root cert is generated in image build
#auto_https: disable_certs
apps:
  layer4:
    servers:
      ssh:
        listen:
          - ":22"
        routes:
          - match:
              - ssh: {}
            handle:
              - handler: proxy
                upstreams:
                  - dial:
                      - "github.com:22"
      http:
        listen:
          - ":80"
        routes:
          - match:
              - http: []
            handle:
              - handler: proxy
                upstreams:
                  - dial:
                      - "{l4.http.host}:80"

      https:
        listen:
         - ":443"
        routes:
          # git-auth-proxy intercept github.com
          # TODO: caching for releases and packages
          - match:
              - tls:
                  sni:
                    - 'github.com'
                    - '*.github.com'
                    - 'ghcr.io'
                    - '*.ghcr.io'
            handle:
              - handler: tls
                connection_policies:
                  - alpn:
                    - http/1.0
                    - http/1.1
                    - http/2
              - handler: proxy
                # proxy_protocol: v2
                upstreams:
                  - dial:
                    - "#{ $GITHUB_PROXY_HOST }:#{ $GITHUB_PROXY_PORT }"
          - match:
             - tls:
                  alpn:
                    - http/1.0
                    - http/1.1
                    - http/2
            handle:
              - handler: tls
                connection_policies:
                  - alpn:
                    - http/1.0
                    - http/1.1
                    - http/2
              - handler: proxy
                upstreams:
                  - dial:
                      - "{l4.tls.server_name}:443"
                    tls: {}
  tls:
    certificates:
      automate:
        - "*"
    # https://caddyserver.com/docs/json/apps/tls/automation/policies/
    automation:
      policies:
        - on_demand: true
          # storage: ...
          reuse_private_keys: true
          issuers:
            - module: internal

#auto_https: disable_certs
