---
services:
  container-socket-proxy:
    build: 
      context: sidecars/container-socket-proxy
      dockerfile: Dockerfile
    image: localhost/l7/container-socket-proxy:latest
    networks:
      container-control:
        ipv4_address: 10.7.9.2
    environment:
      - ALLOW_START=1 #optional
      - ALLOW_STOP=1 #optional
      - ALLOW_RESTARTS=1 #optional
      - AUTH=0 #optional
      - BUILD=0 #optional
      - COMMIT=0 #optional
      - CONFIGS=0 #optional
      - CONTAINERS=0 #optional
      - DISABLE_IPV6=1 #optional
      - DISTRIBUTION=0 #optional
      - EVENTS=1 #optional
      - EXEC=1 #optional
      - IMAGES=0 #optional
      - INFO=1 #optional
      - LIBPOD=1 #optional
      - NETWORKS=0 #optional
      - NODES=0 #optional
      - PING=1 #optional
      - POST=1 #optional
      - PLUGINS=0 #optional
      - SECRETS=0 #optional
      - SERVICES=0 #optional
      - SESSION=0 #optional
      - SWARM=0 #optional
      - SYSTEM=0 #optional
      - TASKS=0 #optional
      - VERSION=1 #optional
      - VOLUMES=0 #optional
    volumes:
      #- /run/user/1000/podman/podman.sock:/var/run/docker.sock
      - ${CONTAINER_SOCKET}:/var/run/docker.sock:ro
      #- /run/user/${UID}/podman/podman.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    #read_only: true

  auth-proxy:
    build:
      context: sidecars/git-auth-proxy
      dockerfile: Dockerfile
    image: localhost/l7/git-auth-proxy:latest
    networks:
      svcs:
        ipv4_address: 10.7.7.135
      public:
    ports:
      - 18774:8080
    volumes:
      - ${HOME}/.config/l7ide/config/git-auth-proxy:/etc/git-auth-proxy
    command:
      - --config
      - /etc/git-auth-proxy/config.json
      - --addr
      - 0.0.0.0:8080
  dns:
    build:
      context: sidecars/dnsmasq
      dockerfile: Containerfile
    image: localhost/l7/dnsmasq:latest
    ports:
      - "18753:53/tcp"
      - "18753:53/udp"
      #- "18767:67/udp"
      #- "18769:69/udp"
    cap_add:
      - NET_ADMIN
    # todo: dynamic for subnets
    command: --address="/#/10.7.8.132"
    networks:
      internal:
        ipv4_address: 10.7.8.133
      svcs:
        ipv4_address: 10.7.7.133
      public:

  # package cache
  apt-cacher-ng:
    build:
      context: sidecars/apt-cacher-ng
      dockerfile: Containerfile
    image: localhost/l7/apt-cacher-ng
    restart: always
    init: true
    #cap_drop:
    #  - all
    networks:
      svcs:
        ipv4_address: 10.7.7.136
    ports:
    - "13142:13142"
    volumes:
    - ${HOME}/.local/share/l7ide/apt-cacher-ng/cache:/var/cache/apt-cacher-ng
    - ${HOME}/.local/share/l7ide/apt-cacher-ng/log:/var/log/apt-cacher-ng

  http-proxy:
    build:
      context: sidecars/caddy
      dockerfile: Containerfile
    image: localhost/l7/caddy
    environment:
      GITHUB_PROXY_HOST: 10.7.7.135
      GITHUB_PROXY_PORT: '8080'
      PKG_PROXY_HOST: 10.7.7.136
      PKG_PROXY_PORT: '13142'
    networks:
      internal:
        ipv4_address: 10.7.8.132
      svcs:
        ipv4_address: 10.7.7.132
      public:
    ports:
      - 18780:80
      - 18743:443
    volumes:
      - ${HOME}/.config/l7ide/config/caddy:/config
      #- ${HOME}/.local/share/l7ide/caddy/data:/data

networks:
  svcs:
    attachable: false
    ipam:
      config:
        - subnet: 10.7.7.0/24
    driver: bridge
    driver_opts:
      inhibit_ipv4: 1
  internal:
    attachable: true
    ipam:
      config:
        - subnet: 10.7.8.0/24
    driver: bridge
    driver_opts:
      inhibit_ipv4: 1
      disable_dns: 1
  container-control:
    attachable: true
    ipam:
      config:
        - subnet: 10.7.9.0/29
          ip_range: 10.7.9.4/30
    driver: bridge
    driver_opts:
      inhibit_ipv4: 1
      disable_dns: 1
  # has external network gateway = internet access
  public:
    attachable: false
    driver: bridge
