---
include:
  - path: compose/proxies.compose.yml
    project_directory: .

services:
  dev-shell:
    profiles:
      - dev
    depends_on:
      - container-socket-proxy
      - dns
      - http-proxy
    build:
      context: .
      dockerfile: Containerfile.nvim
    image: 'localhost/l7/nvim:latest'
    hostname: dev
    restart: always
    user: '1000:1000'
    userns_mode: 'keep-id:uid=1000,gid=1000'
    networks:
      internal:
      container-control:
    working_dir: "${SRC_DIR:-${L7_SRC_DIR:-/src}}"
    # TODO: mounts for config could be done as configs
    # https://github.com/compose-spec/compose-spec/blob/master/08-configs.md
    volumes:
      - '${CONF_DIR:-${HOME}/.config/l7ide/config}/ssh.d:/home/user/.ssh/config.d:ro'
      - '${CONF_DIR:-${HOME}/.config/l7ide/config}/git:/home/user/.config/git:ro'
      - '${SRC_DIR:-${L7_SRC_DIR:-${PWD}}}:${SRC_DIR:-${L7_SRC_DIR:-${PWD}}}:rshared,nosuid'
      - '${SRC_DIR:-${L7_SRC_DIR:-${PWD}}}:/src:rshared,nosuid'
      - '${LOCAL_DIR:-l7_dev_user_local}:/home/user/.local'
      - 'nvim_state:/home/user/.local/state/nvim:z'
      - 'cache_node_yarn_berry:/home/node/.yarn/cache/berry:z,ro'
      - 'cache_node_yarn_classic:/home/node/.cache/yarn:z,ro'
      - 'cache_node_pnpm:/home/node/.cache/pnpm:z,ro'
      - 'cache_node_npm:/home/node/.npm/_cacache:z,ro'
      - target: /tmp
        type: tmpfs
        tmpfs:
          size: 2G
          mode: 0777
      - '${SSH_SOCKET:-${SSH_AUTH_SOCK:-/dev/null}}:${HOME}/.ssh/SSH_AUTH_SOCK'
    env_file:
      - path: env
        required: false
      - path: "${HOME}/.config/l7ide/config/env"
        required: false
    environment:
      CONTAINER_DNS:     '${CONTAINER_DNS:-10.7.8.133}'
      CONTAINER_HOST:    'tcp://10.7.9.2:2375'
      GO_RUNNER_IMAGE:   'localhost/l7/go:1.20-bookworm'
      GPG_IMAGE:         'localhost/l7/gpg-vault:pk'
      NODE_RUNNER_IMAGE: 'localhost/l7/node'
      L7_NODE_VERSION:   '20'
      HOME:    /home/user
      SRC_DIR: '${SRC_DIR:-${L7_SRC_DIR:-/src}}'
      L7_NVIM_STATE_PATH:  'l7_nvim_state'
      L7_NPM_CACHE_VOLUME:  'l7_cache_node_npm'
      L7_PNPM_CACHE_VOLUME: 'l7_cache_node_pnpm'
      L7_YARN_BERRY_CACHE_VOLUME:   'l7_cache_node_yarn_berry'
      L7_YARN_CLASSIC_CACHE_VOLUME: 'l7_cache_node_yarn_classic'
      GPG_PK_VOLUME: 'l7_gpgvault_pk'
      L7_COMPOSE_NETWORK_NAME_INTERNAL: 'l7_dev_internal'
    dns: '${CONTAINER_DNS:-10.7.8.133}'
    entrypoint: /bin/sh
    command: -c 'sleep 36000000000'

#########################################################

volumes:
  user_local:
    name: l7_dev_user_local
  caddy_conf:
    name: l7_caddy_fwd_config
  cache_node_npm:
    name: l7_cache_node_npm
  cache_node_pnpm:
    name: l7_cache_node_pnpm
  cache_node_yarn_berry:
    name: l7_cache_node_yarn_berry
  cache_node_yarn_classic:
    name: l7_cache_node_yarn_classic
  nvim_state:
    name: l7_nvim_state
  gpgvault_pk:
    name: l7_gpgvault_pk
  verdaccio_storage:
    name: l7_dev_verdaccio_storage

networks:
  internal:
    name: l7_dev_internal
    attachable: true
    ipam:
      config:
        - subnet: 10.7.8.0/24
          ip_range: 10.7.8.0/27
    driver: bridge
    driver_opts:
      inhibit_ipv4: 1
      disable_dns: 1
  container-control:
    name: l7_dev_container_control
    attachable: true
    ipam:
      config:
        - subnet: 10.7.9.0/29
          ip_range: 10.7.9.4/30
    driver: bridge
    driver_opts:
      disable_dns:  1
      inhibit_ipv4: 1
