enableStrictSettings: false
enableTelemetry: false
nodeLinker: node-modules
networkConcurrency: 50

npmRegistryServer: "${NPM_CONFIG_REGISTRY:-https://registry.yarnpkg.com}"

httpsCaFilePath: /usr/local/share/ca-certificates/l7-fwd-proxy.crt
httpsCertFilePath: /usr/local/share/ca-certificates/l7-fwd-proxy.crt
caFilePath: /usr/local/share/ca-certificates/l7-fwd-proxy.crt

#logFilters:
#  - code: YN0004
#    level: discard
