# syntax=docker/dockerfile:1.4-labs
ARG ALPINE_VERSION=3.20
ARG BASE_IMAGE=alpine:${ALPINE_VERSION}
FROM ${BASE_IMAGE}

ARG EXTRA_PKGS=''

ARG UID=1000
ARG GID=1000

USER root

RUN apk add --no-cache \
    font-anonymous-pro-nerd \
    font-jetbrains-mono-nerd \
    font-source-code-pro-nerd \
    font-terminus-nerd \
    font-nerd-fonts-symbols \
    nerd-fonts \
    # nerd-fonts-all \
    font-adobe-source-code-pro ttf-dejavu \
    font-terminus \
    font-inconsolata \
    font-dejavu \
    font-awesome \
    font-vollkorn font-misc-cyrillic font-mutt-misc font-screen-cyrillic \
    font-noto font-noto-emoji font-noto-extra font-noto-symbols font-noto-thai \
    # font-noto-cjk \
    font-ipa font-sony-misc font-jis-misc \
    mesa-dri-gallium mesa-vulkan-swrast xf86-video-fbdev xf86-video-vesa \
    xbindkeys xkeyboard-config xsetroot xsel \
    scrot feh

RUN mkdir -p /tmp/.X11-unix && chmod 177 /tmp/.X11-unix

COPY ./skel/ /home/user/
#COPY ./bin/* /usr/local/bin/

RUN touch /home/user/.Xauthority \
    && chmod 600 /home/user/.Xauthority \
    && chown -R ${UID}:${GID} /home/user

USER user
