name: 'oci-image'
on:
  push:
    branches: main
  pull_request:

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 80:5000
    strategy:
      fail-fast: false
      matrix:
        # test with nonstandard uid and gid
        build-args:
          - |
            UID=1234
            GID=1235
          - |
            UID=1000
            GID=1000
          - ''
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build and load caddy image
        uses: docker/build-push-action@v6
        with:
          context: sidecars/caddy
          file: sidecars/caddy/Containerfile
          load: true
          tags: localhost/l7/caddy:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and load nvim image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Containerfile
          build-args: ${{ matrix.build-args }}
          load: true
          tags: l7/nvim:latest
          # could enable push to gh registry
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and load node-runner image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: sidecars/node-runner/Containerfile
          build-args: ${{ matrix.build-args }}
          load: true
          tags: l7/node:20-bookworm
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and load gpg-vault-pk image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: sidecars/gpg-vault-pk/Containerfile
          build-args: ${{ matrix.build-args }}
          load: true
          tags: l7/gpg-vault:pk
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

  test-make:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - auth_proxy
          - gpg_pk
          - nvim
          - runner_node
        cmd:
          - ''
          - docker
          - podman
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: make image_${{ matrix.image }}
      - run: make inspect_${{ matrix.image }}
      - run: make test_${{ matrix.image }}
    env:
      CMD: ${{ matrix.cmd }}
