name: 'oci-image'
on:
  push:
    branches: main
  pull_request:

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 80:5000
    strategy:
      fail-fast: false
      matrix:
        # test with nonstandard uid and gid
        build-args:
          - |
            CADDY_IMAGE=localhost/l7/caddy:latest
            UID=1234
            GID=1235
          - |
            CADDY_IMAGE=localhost/l7/caddy:latest
        include:
          - name: auth-proxy
            file: sidecars/git-auth-proxy/Dockerfile
            context: sidecars/git-auth-proxy
            tags: localhost/l7/auth-proxy:latest
          - name: dnsmasq
            file: sidecars/dnsmasq/Containerfile
            context: sidecars/dnsmasq
            tags: localhost/l7/dnsmasq:latest
          - name: gpg-vault
            file: sidecars/gpg-vault-pk/Containerfile
            context: .
            tags: localhost/l7/gpg-vault:latest
          - name: node
            file: sidecars/node-runner/Containerfile
            context: .
            tags: |
              localhost/l7/node:latest
              localhost/l7/node:20-bookworm
          - name: nvim
            file: Containerfile
            context: .
            tags: localhost/l7/nvim:latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: allow cleartext http to localhost container registry
        run: |
          echo '{"insecure-registries" : [ "localhost" ]}' | sudo tee /etc/docker/daemon.json

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build and load caddy image
        if: ${{ matrix.name == 'nvim' || matrix.name == 'node' }}
        uses: docker/build-push-action@v6
        with:
          context: sidecars/caddy
          file: sidecars/caddy/Containerfile
          tags: localhost/l7/caddy:latest
          load: true
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and load ${{ matrix.name }} image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          build-args: ${{ matrix.build-args }}
          tags:  ${{ matrix.tags }}
          load: true
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

  test-make:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - auth_proxy
          - caddy
          - dnsmasq
          - gpg_pk
          - nvim
          - runner_node
        cmd:
          - ''
          - docker
          - podman
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: make image_${{ matrix.image }}
      - run: make inspect_${{ matrix.image }}
      - run: make test_${{ matrix.image }}
    env:
      CMD: ${{ matrix.cmd }}
